[package]
name = "mux-client"
version = "0.6.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
directories.workspace = true
mux-acp = { path = "../mux-acp" }
mux-protocol = { path = "../mux-protocol" }
mux-terminal = { path = "../mux-terminal" }
mux-workspace = { path = "../mux-workspace" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
